services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["quasar", "dev"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

networks:
  default:
    name: upunreal
