name: Deploy Frontend to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Quasar App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build Quasar App
        working-directory: client
        run: quasar build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./client/dist/spa
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
